name: Test CSharp NuGet

on:
  push:
    branches: [ main ]

jobs:
  test-nuget:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        name: [Ubuntu, macOS, Windows64, Windows32]
        include:
        - name: Ubuntu
          os: ubuntu-latest
          platform: linux-x64
          arch: x64
        - name: macOS
          os: macos-latest
          platform: macOS-x64
          arch: x64
        - name: Windows64
          os: windows-latest
          platform: win
          arch: x64
        - name: Windows32
          os: windows-latest
          platform: win
          arch: x86

    steps:
      - uses: actions/checkout@v3

      - name: test nuget
        run: |
          dotnet restore OpenStudio.Tests.csproj
          dotnet add OpenStudio.Tests.csproj package NREL.OpenStudio.${{ matrix.platform }}
          dotnet test OpenStudio.Tests.csproj --arch ${{ matrix.arch }}